# Generated by Django 2.2.10 on 2022-05-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='ServiceCase',
        ),
    ]
