# Generated by Django 2.2.10 on 2022-05-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220526_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecase',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecase',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
