# Generated by Django 4.1.3 on 2022-11-02 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('_id', models.CharField(max_length=8, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='UTEP Email')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCheckIn',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, editable=False, verbose_name='Date')),
                ('time_in', models.TimeField(blank=True, default=None, null=True)),
                ('auto_time_in', models.TimeField(blank=True, editable=False, verbose_name='R-Time In')),
                ('time_out', models.TimeField(blank=True, default=None, null=True)),
                ('auto_time_out', models.TimeField(blank=True, default=None, null=True, verbose_name='R-Time Out')),
                ('is_on_clock', models.BooleanField(default=True)),
                ('image_proof', models.TextField(blank=True, max_length=100, null=True)),
                ('timed_out', models.BooleanField(default=False, verbose_name='Auto-Timed Out')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='coba.student', verbose_name='Student/Employee Name')),
            ],
            options={
                'verbose_name': 'historical check in',
                'verbose_name_plural': 'historical check ins',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('time_in', models.TimeField(blank=True, default=None, null=True)),
                ('auto_time_in', models.TimeField(auto_now_add=True, verbose_name='R-Time In')),
                ('time_out', models.TimeField(blank=True, default=None, null=True)),
                ('auto_time_out', models.TimeField(blank=True, default=None, null=True, verbose_name='R-Time Out')),
                ('is_on_clock', models.BooleanField(default=True)),
                ('image_proof', models.ImageField(blank=True, null=True, upload_to='images/clockout/')),
                ('timed_out', models.BooleanField(default=False, verbose_name='Auto-Timed Out')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coba.student', verbose_name='Student/Employee Name')),
            ],
        ),
    ]
