# Generated by Django 4.0.2 on 2022-02-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
