# Generated by Django 4.0.2 on 2022-02-07 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coba', '0002_checkin_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='image_proof',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/clockout/'),
            preserve_default=False,
        ),
    ]
