# Generated by Django 4.1 on 2022-09-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coba', '0003_checkin_image_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='image_proof',
            field=models.ImageField(blank=True, null=True, upload_to='images/clockout/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='_id',
            field=models.CharField(blank=True, max_length=8, verbose_name='ID'),
        ),
    ]
