# Generated by Django 4.2.1 on 2023-05-17 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ashkan", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkin",
            name="auto_time_in",
        ),
        migrations.RemoveField(
            model_name="checkin",
            name="auto_time_out",
        ),
        migrations.RemoveField(
            model_name="historicalcheckin",
            name="auto_time_in",
        ),
        migrations.RemoveField(
            model_name="historicalcheckin",
            name="auto_time_out",
        ),
        migrations.AddField(
            model_name="checkin",
            name="time_in",
            field=models.TimeField(
                default=datetime.datetime(2023, 5, 17, 11, 8, 8, 96594),
                verbose_name="Time In",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="time_out",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="Time Out"
            ),
        ),
        migrations.AddField(
            model_name="historicalcheckin",
            name="time_in",
            field=models.TimeField(
                default=datetime.datetime(2023, 5, 17, 11, 8, 8, 96594),
                verbose_name="Time In",
            ),
        ),
        migrations.AddField(
            model_name="historicalcheckin",
            name="time_out",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="Time Out"
            ),
        ),
    ]
